services:
  oweme.api:
    image: oweme.api
    container_name: OweMeApi
    build:
      context: .
      dockerfile: api/src/OweMe.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - Serilog__WriteTo__0__Name=Console
      - Database__ConnectionString=Server=oweme.api.database;Database=OweMe.Api;Username=sa;Password=Password123;TrustServerCertificate=True;
      - Database__RunMigrations=true
    depends_on:
      oweme.api.database:
        condition: service_healthy

  oweme.api.database:
    image: "postgres:15.3"
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=OweMe.Api
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5